# Generated by Django 4.2.6 on 2023-10-17 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_alter_customuser_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='verified_email',
            field=models.BooleanField(default=False),
        ),
    ]
