# Generated by Django 4.2.6 on 2023-10-17 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_jobboard', '0007_alter_job_id_alter_jobapplication_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='application_deadline',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
