# Generated by Django 4.2.6 on 2023-10-18 12:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_jobboard', '0009_alter_job_currency_alter_job_employer_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='application_deadline',
        ),
    ]
