# Generated by Django 4.2.6 on 2023-10-19 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_jobboard', '0012_alter_search_options_search_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='search',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
