# Generated by Django 4.2.6 on 2023-10-19 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_jobboard', '0013_search_updated'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='summary',
            field=models.TextField(default='f', max_length=255),
            preserve_default=False,
        ),
    ]
