# Generated by Django 4.2.6 on 2023-10-21 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_jobboard', '0016_remove_job_category_remove_job_company_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='name',
            field=models.CharField(max_length=256),
        ),
        migrations.AlterField(
            model_name='job',
            name='salary',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='skills_required',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='summary',
            field=models.TextField(max_length=256),
        ),
    ]
