# Generated by Django 4.2.6 on 2023-10-23 18:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_jobboard', '0017_alter_company_name_alter_job_salary_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='currency',
        ),
    ]
