# Generated by Django 4.2.6 on 2023-10-24 09:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app_jobboard', '0020_company_description_company_islookingforemployees_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyreviews',
            name='company',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app_jobboard.company'),
        ),
        migrations.AlterField(
            model_name='companyreviews',
            name='reviewer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
