# Generated by Django 4.2.6 on 2023-11-03 14:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_jobboard', '0024_company_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companyreviews',
            name='company',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app_jobboard.company'),
        ),
    ]
